# Generated by Django 3.2.19 on 2023-05-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
    ]
